### PR TITLE
Packaging Brouhaha

### PR DESCRIPTION
**Pull request by hadware**
As suggested and required (#3 ) by @hbredin, here's a pull request to add:
- a proper `setup.py`
- a CI to check if the package setup runs fine

Also, i removed stuff that dated back to the old VTC repo

I can add a release to pipy if that's something ideal for an huggingface release.

### CODE REVIEW

**Comment by hbredin** [comment]
There was an issue in `setup.py` that I have now fixed.

**Comment by hbredin** [comment]
I am wondering whether it would be a good idea to rename `brouhaha_vtc` to something simpler like `brouhaha`. 

What do you think @marianne-m @MarvinLvn @hadware?

It would also mean updating the checkpoint so that it links to `brouhaha.xxx` rather than `brouhaha_vtc.xxx`.

**Comment by hadware** [comment]
(@marianne-m you were right, I had forgotten to push my changes)

> What do you think @marianne-m @MarvinLvn @hadware?

Well, I changed the folder name to `brouhaha-vad`, but just `brouhaha` is fine with me as well.

**Comment by marianne-m** [comment]
I agree, a simpler name like `brouhaha` is a good idea.

**Comment by hadware** [comment]
Done!

**Comment by hbredin** [comment]
Thanks.

The checkpoint needs to be updated as well because this will now fail:

```python
from pyannote.audio import Model
model = Model.from_pretrained("models/best/checkpoints/best.ckpt")
# ModuleNotFoundError: No module named 'brouhaha_vtc'
```

This is because the checkpoint has the following keys used by `pyannote.audio` to load the model:

```python
checkpoint["pyannote.audio"]["architecture"]["class"]
# "CustomPyanNetModel"
checkpoint["pyannote.audio"]["architecture"]["module"]
# "brouhaha_vtc.models"  <-- this should be "brouhaha.models"
```

**Comment by marianne-m** [comment]
The checkpoint has been updated !

**Review by hbredin — APPROVED** [review]
LGTM

**Comment by hbredin** [comment]
:tada: I've updated [hf.co/pyannote/brouhaha](https://hf.co/pyannote/brouhaha) README accordingly.

**Pull request merged**
